# docker-compose.yml
version: "2"
services:
  app:
    container_name: server_file
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py
#    volumes:
#      - /usr/local/volumes/fileserver/uploads/:/app/uploads/:rw
    ports:
      - "4444:4444"