# docker-compose_dev.yml
version: "2"
services:
  app:
    container_name: server_file_dev
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py
    volumes:
      - /usr/local/volumes/fileserver/uploads/:/app/uploads/:rw
    ports:
      - "4545:4545"